name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: public
    - run: |
        cd public
        touch hehe
        git add hehe
        git commit -m "test"
        git config --global user.email "oyanglulu@gmail.com"
        git config --global user.name "orgpress"
        git push origin gh-pages
